2020-07-01 17:55:03,763 Using selector: EpollSelector
2020-07-01 17:55:06,798 Exception on /ETfDescription/EtfData/XLK/20200608 [GET]
Traceback (most recent call last):
  File "/home/piyush/Desktop/etf1903/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/piyush/Desktop/etf1903/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/piyush/Desktop/etf1903/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/piyush/Desktop/etf1903/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/piyush/Desktop/etf1903/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/piyush/Desktop/etf1903/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/piyush/Desktop/etf1903/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/piyush/Desktop/etf/ETFAnalyzer/FlaskAPI/server.py", line 77, in SendETFHoldingsData
    req = request.__dict__['environ']['REQUEST_URI']
KeyError: 'REQUEST_URI'
2020-07-01 17:55:07,848 Command saslStart with request id 1649760492 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:08,036 Command saslStart with request id 1649760492 on server ('18.213.229.80', 27017) succeeded in 188331 microseconds
2020-07-01 17:55:08,053 Command saslContinue with request id 596516649 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:08,242 Command saslContinue with request id 596516649 on server ('18.213.229.80', 27017) succeeded in 188463 microseconds
2020-07-01 17:55:08,243 Command saslContinue with request id 1189641421 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:08,522 Command saslContinue with request id 1189641421 on server ('18.213.229.80', 27017) succeeded in 278559 microseconds
2020-07-01 17:55:08,524 Command find with request id 1025202362 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:08,731 Command find with request id 1025202362 on server ('18.213.229.80', 27017) succeeded in 206301 microseconds
2020-07-01 17:55:09,369 Command saslStart with request id 1102520059 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:09,651 Command saslStart with request id 1102520059 on server ('18.213.229.80', 27017) succeeded in 282132 microseconds
2020-07-01 17:55:09,672 Command saslContinue with request id 2044897763 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:09,870 Command saslContinue with request id 2044897763 on server ('18.213.229.80', 27017) succeeded in 197884 microseconds
2020-07-01 17:55:09,871 Command saslContinue with request id 1967513926 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:10,146 Command saslContinue with request id 1967513926 on server ('18.213.229.80', 27017) succeeded in 274712 microseconds
2020-07-01 17:55:10,146 Command find with request id 1365180540 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:10,598 Command find with request id 1365180540 on server ('18.213.229.80', 27017) succeeded in 451510 microseconds
2020-07-01 17:55:15,910 Command find with request id 1303455736 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:17,829 Command find with request id 1303455736 on server ('18.213.229.80', 27017) succeeded in 1918732 microseconds
2020-07-01 17:55:17,833 Command find with request id 35005211 started on server ('18.213.229.80', 27017)
2020-07-01 17:55:18,269 Command find with request id 35005211 on server ('18.213.229.80', 27017) succeeded in 435713 microseconds
